"""empty message

Revision ID: 043e2ba92f71
Revises: 1ab01b72bd78
Create Date: 2025-07-04 21:34:24.645429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '043e2ba92f71'
down_revision = '1ab01b72bd78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('Post_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'post', ['Post_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', postgresql.ENUM('IMAGE', 'VIDEO', 'Audio', name='mediatype'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Post_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
